---
- name: Provision EC2 instace using Ansible Playbook
  hosts: localhost
  connection: local
  gather_facts: false
  tags: EC2 provisioning

  vars:
    instnace_type: t2.medium
    image: ami-0bb6af715826253bf
    wait: 500
    count: 1
    regsion: us-wast-1
    security_group: sg-008147de9733254d3
    instnace_tags:
      name: Jenkins
      OS: CentOS
    monitoring: no
    vpc_subnet_id: subnet-0e38aebc4c64b3e50
    assign_public_ip: yes
    register: ec2
    delegate_to: localhost

- name: Wait for SSH to come up
    local_action:
      module: wait_for
      host: "{{ item.public_ip }}"
      port: 22
      delay: 10
      timeout: 120
    loop: "{{ ec2.instances }}"
    # By specifying never on the tag of this block,
    # I let this block to run only when explicitely being called
    tags: ['never', 'ec2-create']